In [1]:
import numpy as np

In [2]:
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

In [5]:
a+1

array([[2, 3],
       [4, 5]])

In [6]:
b-2

array([[ 2,  1],
       [ 0, -1]])

In [7]:
a+b

array([[5, 5],
       [5, 5]])

In [9]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [11]:
np.hstack((a, b))

array([[1, 2, 4, 3],
       [3, 4, 2, 1]])

In [14]:
c = [6,7]

In [15]:
np.column_stack((a, c))

array([[1, 2, 6],
       [3, 4, 7]])

In [18]:
a = np.concatenate((a, b), 1)
a

array([[1, 2, 4, 3],
       [3, 4, 2, 1]])

In [19]:
np.hsplit(a, 2)

[array([[1, 2],
        [3, 4]]),
 array([[4, 3],
        [2, 1]])]

In [20]:
np.vsplit(a, 2)

[array([[1, 2, 4, 3]]), array([[3, 4, 2, 1]])]

In [25]:
#broadcasting
a = np.array([1, 2 , 3, 4])
b = np.array([5, 6, 7])
a[:, np.newaxis] + b

array([[ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11]])

In [28]:
#sorting
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)
arr1

array([[10,  1],
       [12, 15]])

In [29]:
arr2 = np.sort(a, axis = -1)
arr2

array([[12, 15],
       [ 1, 10]])

In [30]:
arr1 = np.sort(a, axis = None)
arr1

array([ 1, 10, 12, 15])

In [31]:
a = np.array([9, 3, 1, 7, 4, 3, 6])
b = np.argsort(a)
b

array([2, 1, 5, 4, 6, 3, 0], dtype=int64)

In [32]:
c = np.zeros(len(b), dtype = int)
for i in range(0, len(b)):
    c[i]= a[b[i]]
c

array([1, 3, 3, 4, 6, 7, 9])