In [2]:
#Arrays are homogenous, i.e. all elements are of same type.

import numpy as np

In [57]:
list1 = [1,2,3,4,5]
array_1d = np.array(list1)
print(array_1d)
print(type(array_1d))
print(array_1d.dtype)
print(array_1d.shape)
print(array_1d.size)
print(array_1d.ndim)
print(array_1d.itemsize)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)
5
1
8


In [58]:
list2 = [6,7,8,9,10]
array_2d = np.array([list1,list2])
print(array_2d)
print(type(array_2d))
print(array_2d.dtype)
print(array_2d.shape)
print(array_2d.size)
print(array_2d.ndim)
print(array_2d.itemsize)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
int64
(2, 5)
10
2
8


In [59]:
list3 = [11,12,13,14,15]
array_3d = np.array([list1,list2,list3])
print(array_3d)
print(type(array_3d))
print(array_3d.dtype)
print(array_3d.shape)
print(array_3d.size)
print(array_3d.ndim)
print(array_3d.itemsize)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>
int64
(3, 5)
15
2
8


In [13]:
#Multiplying 2 lists in python way
product1 = list(map(lambda x,y:x*y,list1,list2))
print(product1)

[6, 14, 24, 36, 50]


In [ ]:
#Multiplying 2 arrays in numpy way
product2 = np.array(list1) * np.array(list2)
print(product2)

#Adding 2 arrays
add1 = np.array(list1) + np.array(list2)
print(add1)

[ 6 14 24 36 50]
[ 7  9 11 13 15]


In [28]:
#Squaring arrays    
square1 = np.array(list1) ** 2
square1

array([ 1,  4,  9, 16, 25])

In [19]:
array_from_list = np.array([2, 5, 6, 7]) 
array_from_tuple = np.array((4, 5, 8, 9))
print(array_from_list)
print(array_from_tuple)

[2 5 6 7]
[4 5 8 9]


In [26]:
#Other ways of creating arrays
arr1 = np.zeros(5)
arr2 = np.ones([5,8], dtype=np.int64)
arr1

array([0., 0., 0., 0., 0.])

In [27]:
arr2

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [31]:
np.ones((5,8), dtype=np.int64)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [30]:
np.random.random([3,5])

array([[0.65469522, 0.39723824, 0.65602931, 0.71697823, 0.43380531],
       [0.44687525, 0.67354494, 0.36454656, 0.93240112, 0.40585867],
       [0.27019907, 0.13985508, 0.66362164, 0.25787242, 0.70985652]])

In [32]:
range1 = np.arange(10, 100, 5)
range1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [35]:
linspace1 = np.linspace(10, 40, 5)
linspace1

array([10. , 17.5, 25. , 32.5, 40. ])

In [ ]:
#np.full: Returns a new array of given shape and type, filled with a particular value.
#np.tile(): Create a new array — by repeating an existing array — for a particular number of times
# np.eye(): Create an identity matrix of any dimension

In [26]:
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [27]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [22]:
a = np.array([[0,1],[1,0]])
np.tile(a, (2,2))

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [28]:
np.random.randint(0, 10, (4,4))

array([[1, 4, 4, 9],
       [3, 9, 6, 6],
       [9, 4, 8, 7],
       [2, 7, 4, 1]], dtype=int32)

In [ ]:
#3d array
array_3d = np.arange(24).reshape(2, 3, 4)
array_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
ar_1 = np.arange(10,35,3)
ar_1

array([10, 13, 16, 19, 22, 25, 28, 31, 34])

In [51]:
print(ar_1[3])
print(ar_1[[2, 5, 6]]) #index as a list
print(ar_1[2:]) #slicing after 3rd element
print(ar_1[:3]) #slicing first 3 elements
print(ar_1[2:7]) #slicing 2nd to 6th element
print(ar_1[2::3]) #slicing every 3rd element

19
[16 25 28]
[16 19 22 25 28 31 34]
[10 13 16]
[16 19 22 25 28]
[16 25 34]


In [53]:
# Iterations are also similar to lists
for i in ar_1:
    print(i**3)

1000
2197
4096
6859
10648
15625
21952
29791
39304


In [60]:
# Creating a 2-D array
arr_2d = np.array([list1, list2, list3])
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [61]:
# Third row second column
print(arr_2d[2, 1])

12


In [62]:
# Slicing the second row, and all columns
arr_2d[1, :]

array([ 6,  7,  8,  9, 10])

In [63]:
# Slicing all rows and the third column
arr_2d[:, 2]

array([ 3,  8, 13])

In [64]:
# Slicing all rows and the first three columns
arr_2d[:, :3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])