In [3]:
#Arrays are homogenous, i.e. all elements are of same type.

import numpy as np

In [10]:
list1 = [1,2,3,4,5]
array_1d = np.array(list1)
print(array_1d)
print(type(array_1d))
print(array_1d.dtype)
print(array_1d.shape)
print(array_1d.size)
print(array_1d.ndim)
print(array_1d.itemsize)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)
5
1
8


In [12]:
list2 = [6,7,8,9,10]
array_2d = np.array([list1,list2])
print(array_2d)
print(type(array_2d))
print(array_2d.dtype)
print(array_2d.shape)
print(array_2d.size)
print(array_2d.ndim)
print(array_2d.itemsize)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
int64
(2, 5)
10
2
8


In [8]:
list3 = [11,12,13,14,15]
array_3d = np.array([list1,list2,list3])
print(array_3d)
print(type(array_3d))
print(array_3d.dtype)
print(array_3d.shape)
print(array_3d.size)
print(array_3d.ndim)
print(array_3d.itemsize)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>
int64
(3, 5)
15
2
8


In [13]:
#Multiplying 2 lists in python way
product1 = list(map(lambda x,y:x*y,list1,list2))
print(product1)

[6, 14, 24, 36, 50]


In [ ]:
#Multiplying 2 arrays in numpy way
product2 = np.array(list1) * np.array(list2)
print(product2)

#Adding 2 arrays
add1 = np.array(list1) + np.array(list2)
print(add1)

[ 6 14 24 36 50]
[ 7  9 11 13 15]


In [28]:
#Squaring arrays    
square1 = np.array(list1) ** 2
square1

array([ 1,  4,  9, 16, 25])

In [19]:
array_from_list = np.array([2, 5, 6, 7]) 
array_from_tuple = np.array((4, 5, 8, 9))
print(array_from_list)
print(array_from_tuple)

[2 5 6 7]
[4 5 8 9]


In [26]:
#Other ways of creating arrays
arr1 = np.zeros(5)
arr2 = np.ones([5,8], dtype=np.int64)
arr1

array([0., 0., 0., 0., 0.])

In [27]:
arr2

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [31]:
np.ones((5,8), dtype=np.int64)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [30]:
np.random.random([3,5])

array([[0.65469522, 0.39723824, 0.65602931, 0.71697823, 0.43380531],
       [0.44687525, 0.67354494, 0.36454656, 0.93240112, 0.40585867],
       [0.27019907, 0.13985508, 0.66362164, 0.25787242, 0.70985652]])

In [32]:
range1 = np.arange(10, 100, 5)
range1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [35]:
linspace1 = np.linspace(10, 40, 5)
linspace1

array([10. , 17.5, 25. , 32.5, 40. ])