In [64]:
#Arrays are homogenous, i.e. all elements are of same type.

import numpy as np

In [65]:
list1 = [1,2,3,4,5]
array_1d = np.array(list1)
print(array_1d)
print(type(array_1d))
print(array_1d.dtype)
print(array_1d.shape)
print(array_1d.size)
print(array_1d.ndim)
print(array_1d.itemsize)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)
5
1
8


In [66]:
list2 = [6,7,8,9,10]
array_2d = np.array([list1,list2])
print(array_2d)
print(type(array_2d))
print(array_2d.dtype)
print(array_2d.shape)
print(array_2d.size)
print(array_2d.ndim)
print(array_2d.itemsize)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
int64
(2, 5)
10
2
8


In [67]:
list3 = [11,12,13,14,15]
array_3d = np.array([list1,list2,list3])
print(array_3d)
print(type(array_3d))
print(array_3d.dtype)
print(array_3d.shape)
print(array_3d.size)
print(array_3d.ndim)
print(array_3d.itemsize)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>
int64
(3, 5)
15
2
8


In [68]:
#Multiplying 2 lists in python way
product1 = list(map(lambda x,y:x*y,list1,list2))
print(product1)

[6, 14, 24, 36, 50]


In [69]:
#Multiplying 2 arrays in numpy way
product2 = np.array(list1) * np.array(list2)
print(product2)

#Adding 2 arrays
add1 = np.array(list1) + np.array(list2)
print(add1)

[ 6 14 24 36 50]
[ 7  9 11 13 15]


In [70]:
#Squaring arrays    
square1 = np.array(list1) ** 2
square1

array([ 1,  4,  9, 16, 25])

In [71]:
array_from_list = np.array([2, 5, 6, 7]) 
array_from_tuple = np.array((4, 5, 8, 9))
print(array_from_list)
print(array_from_tuple)

[2 5 6 7]
[4 5 8 9]


In [72]:
#Other ways of creating arrays
arr1 = np.zeros(5)
arr2 = np.ones([5,8], dtype=np.int64)
arr1

array([0., 0., 0., 0., 0.])

In [73]:
arr2

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [74]:
np.ones((5,8), dtype=np.int64)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [75]:
np.random.random([3,5])

array([[0.98660579, 0.26607081, 0.33749466, 0.62034805, 0.68559814],
       [0.15287629, 0.89023533, 0.88866755, 0.14414397, 0.04221611],
       [0.59068113, 0.28892039, 0.33396971, 0.6705244 , 0.4546048 ]])

In [76]:
range1 = np.arange(10, 100, 5)
range1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [77]:
linspace1 = np.linspace(10, 40, 5)
linspace1

array([10. , 17.5, 25. , 32.5, 40. ])

In [78]:
#np.full: Returns a new array of given shape and type, filled with a particular value.
#np.tile(): Create a new array — by repeating an existing array — for a particular number of times
# np.eye(): Create an identity matrix of any dimension

In [79]:
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [80]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [81]:
a = np.array([[0,1],[1,0]])
np.tile(a, (2,2))

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [82]:
np.random.randint(0, 10, (4,4))

array([[1, 3, 5, 2],
       [3, 9, 9, 1],
       [5, 3, 8, 3],
       [5, 2, 3, 6]], dtype=int32)

In [83]:
#3d array
array_3d = np.arange(24).reshape(2, 3, 4)
array_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [84]:
ar_1 = np.arange(10,35,3)
ar_1

array([10, 13, 16, 19, 22, 25, 28, 31, 34])

In [85]:
print(ar_1[3])
print(ar_1[[2, 5, 6]]) #index as a list
print(ar_1[2:]) #slicing after 3rd element
print(ar_1[:3]) #slicing first 3 elements
print(ar_1[2:7]) #slicing 2nd to 6th element
print(ar_1[2::3]) #slicing every 3rd element

19
[16 25 28]
[16 19 22 25 28 31 34]
[10 13 16]
[16 19 22 25 28]
[16 25 34]


In [86]:
# Iterations are also similar to lists
for i in ar_1:
    print(i**3)

1000
2197
4096
6859
10648
15625
21952
29791
39304


In [87]:
# Creating a 2-D array
arr_2d = np.array([list1, list2, list3])
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [88]:
# Third row second column
print(arr_2d[2, 1])
print(arr_2d[2][1])

12
12


In [89]:
# Slicing the second row, and all columns
arr_2d[1, :]

array([ 6,  7,  8,  9, 10])

In [90]:
# Slicing all rows and the third column
arr_2d[:, 2]

array([ 3,  8, 13])

In [91]:
# Slicing all rows and the first three columns
arr_2d[:, :3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [97]:
#Arrays are mutable
arr_2d[2, 1] = 22
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 22, 13, 14, 15]])

In [98]:
print(arr_2d.shape)
print(arr_2d.ndim)

(3, 5)
2


In [ ]:
#Extracting border elements
a = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(a[:,0], a[0,:], a[:,-1], a[-1,:])

[11 21 31] [11 12 13 14] [14 24 34] [31 32 33 34]


In [117]:
#time complexity
list_1 = [i for i in range(1000000)]
list_2 = [j**2 for j in range(1000000)]

import time

# store start time, time after computation, and take the difference
t0 = time.time()
product_list = list(map(lambda x, y: x*y, list_1, list_2))
t1 = time.time()
list_time = t1 - t0 
print(t1-t0)


# numpy array 
array_1 = np.array(list_1)
array_2 = np.array(list_2)

t0 = time.time()
array_3 = array_1*array_2
t1 = time.time()
numpy_time = t1 - t0

print(t1-t0)

print("The ratio of time taken is {}".format(list_time/numpy_time))

0.10072159767150879
0.0020771026611328125
The ratio of time taken is 48.491391184573004


For horizontal stacking, the number of rows should be the same, while for vertical stacking, the number of columns should be the same.

Reshape

In [ ]:
arr = np.arange(12)
print(type(arr))
print(arr)
print(arr.ndim)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11]
1


In [143]:
a = arr.reshape(3,4)
print(type(a))
print(a)
print(a.ndim)

<class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2


In [139]:
b = arr.reshape(6,2)
print(type(b))
print(b)
print(b.ndim)

<class 'numpy.ndarray'>
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
2


In [145]:
c = b.T
c

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

hstack and vstack

In [146]:
array_1 = np.arange(12).reshape(3, 4)
array_2 = np.arange(20).reshape(5, 4)

print(array_1)
print("\n")
print(array_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [147]:
np.vstack((array_1, array_2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [148]:
np.hstack((array_1, a))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])